version: '3.8'
services:
  n8n:
    image: n8nio/n8n
#    restart: always
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "admin"
      N8N_BASIC_AUTH_PASSWORD: "hippocampus" # CHANGE THIS!
#      N8N_HTTPS: "true"                # Enable HTTPS
#      N8N_TLS_CERT: "/home/node/.n8n/certs/cert.pem"  # Path to certificate
#      N8N_TLS_KEY: "/home/node/.n8n/certs/privkey.pem" # Path to private key
    volumes:
      - /Users/timhansen/Documents/pythonEnvironment/n8n/data:/home/node/.n8n
#      - /Users/timhansen/Documents/pythonEnvironment/n8n/data/certs:/home/node/.n8n/certs

volumes:
  n8n_data: